import { createFileRoute, Link } from '@tanstack/react-router';
import { AppShell } from '@/components/app/AppShell';
import { useEffect, useState } from 'react';
import { getSession } from '@/lib/botlab/auth';
import { listBots } from '@/lib/botlab/bots';
import { listWorkspaces } from '@/lib/botlab/workspaces';

export const Route = createFileRoute('/app')({ component: Dashboard });
function Dashboard(){ const [bots,setBots]=useState<any[]>([]); const [workspaces,setWorkspaces]=useState<any[]>([]); const [loading,setLoading]=useState(true); useEffect(()=>{(async()=>{const s=await getSession(); if(!s.data.session){location.href='/auth';return;} const w=await listWorkspaces(); setWorkspaces(w); if(w[0]?.id){const b=await listBots(w[0].id);setBots(b);} setLoading(false);})()},[]); return <AppShell><div className="p-5 md:p-8"><div className="mb-8"><p className="text-sm font-semibold text-slate-500">Overview</p><h1 className="mt-1 text-3xl font-black tracking-tight">Your AI workspace</h1></div><div className="grid gap-4 md:grid-cols-3"><Stat label="Workspaces" value={workspaces.length}/><Stat label="Active bots" value={bots.filter(b=>b.status==='active').length}/><Stat label="Total bots" value={bots.length}/></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Your bots</h2><p className="mt-1 text-sm text-slate-500">Create an assistant trained on your business.</p></div><Link to="/app/bots/new" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Create bot</Link></div>{loading?<p className="mt-8 text-sm text-slate-500">Loading…</p>:bots.length===0?<div className="mt-8 rounded-xl bg-slate-50 p-8 text-center"><p className="font-semibold">No bots yet</p><p className="mt-1 text-sm text-slate-500">Create your first bot to get started.</p></div>:<div className="mt-6 space-y-2">{bots.map(b=><Link key={b.id} to="/app/bots" className="flex items-center justify-between rounded-xl border border-slate-100 p-4 hover:bg-slate-50"><div><p className="font-semibold">{b.name}</p><p className="text-xs text-slate-500">{b.language.toUpperCase()} · {b.status}</p></div><span className="text-sm text-slate-400">Open →</span></Link>)}</div>}</section></div></AppShell> }
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
