import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { FormEvent, useState } from 'react';
import { AppShell } from '@/components/app/AppShell';
import { createBot } from '@/lib/botlab/bots';
import { createWorkspace, listWorkspaces } from '@/lib/botlab/workspaces';
import { getSession } from '@/lib/botlab/auth';
export const Route=createFileRoute('/app/bots/new')({component:NewBot});
function NewBot(){const nav=useNavigate();const [name,setName]=useState('');const [slug,setSlug]=useState('');const [description,setDescription]=useState('');const [language,setLanguage]=useState('uz');const [prompt,setPrompt]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await getSession();if(!s.data.session)throw new Error('Authentication required');let ws=(await listWorkspaces())[0];if(!ws)ws=await createWorkspace({name:'My Business',slug:`workspace-${s.data.session.user.id.slice(0,8)}`});await createBot(ws.id,{name,slug,description,language:language as 'uz'|'ru'|'en',system_prompt:prompt});nav({to:'/app/bots'});}catch(err:any){setError(err.message||'Could not create bot');}finally{setBusy(false)}}return <AppShell><div className="mx-auto max-w-2xl p-5 md:p-10"><p className="text-sm font-semibold text-slate-500">Bot setup</p><h1 className="mt-1 text-3xl font-black">Create your AI bot</h1><p className="mt-2 text-slate-500">Start with the basics. Knowledge and Telegram can be connected next.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><Field label="Bot name"><input required value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}} placeholder="Acme Assistant"/></Field><Field label="Slug"><input required value={slug} onChange={e=>setSlug(e.target.value)} placeholder="acme-assistant"/></Field><Field label="Description"><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Answers customer questions 24/7"/></Field><Field label="Primary language"><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="uz">O‘zbek</option><option value="ru">Русский</option><option value="en">English</option></select></Field><Field label="AI instructions"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={5} placeholder="You are a helpful sales assistant for our business..."/></Field>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-slate-950 py-3 font-semibold text-white disabled:opacity-50">{busy?'Creating…':'Create bot'}</button></form></div></AppShell>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span>{children}</label>}
