import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { FormEvent, useState } from 'react';
import { signIn, signUp } from '@/lib/botlab/auth';

export const Route = createFileRoute('/auth')({ component: AuthPage });

function AuthPage() {
  const navigate = useNavigate(); const [mode,setMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const result = mode==='login' ? await signIn(email,password) : await signUp(email,password,name); setBusy(false); if(result.error){setError(result.error.message);return;} if(mode==='signup' && !result.data.session){setError('Check your email to confirm your account.');return;} navigate({to:'/app'}); }
  return <div className="grid min-h-screen place-items-center bg-[#f7f8fa] p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8 flex items-center gap-2 text-xl font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white">B</span> BotLab</div><h1 className="text-3xl font-black tracking-tight">{mode==='login'?'Welcome back':'Create your workspace'}</h1><p className="mt-2 text-sm text-slate-500">{mode==='login'?'Sign in to manage your AI bots.':'Start building your first business chatbot.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name" className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-slate-950"/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="Email" className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-slate-950"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} placeholder="Password" className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-slate-950"/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-slate-950 py-3 font-semibold text-white disabled:opacity-50">{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button onClick={()=>setMode(mode==='login'?'signup':'login')} className="mt-5 w-full text-sm font-medium text-slate-600">{mode==='login'?"Don't have an account? Sign up":"Already have an account? Sign in"}</button></div></div>;
}
